name: pmagpy
channels:
  - conda-forge
  - defaults
dependencies:
  - imageio
  - pip
  - gdal
  - cartopy
  - lmfit
  - matplotlib
  - pandas
  - numpy
  - scripttest
  - pyqt
  - habanero
  - scipy
  - xlwt
  - pillow
  - future
  - scikit-learn
  - seaborn
